# Generated by Django 5.2.4 on 2025-07-17 20:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del menú')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_menu', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('MERIENDA', 'Merienda'), ('CENA', 'Cena'), ('ESPECIAL', 'Menú Especial')], max_length=20, verbose_name='Tipo de menú')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'ordering': ['tipo_menu', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad requerida')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='Artículo de inventario')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='Menú')),
            ],
            options={
                'verbose_name': 'Artículo del menú',
                'verbose_name_plural': 'Artículos del menú',
                'unique_together': {('menu', 'inventory_item')},
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(related_name='menus', through='menus.MenuItem', through_fields=('menu', 'inventory_item'), to='inventory.inventory', verbose_name='Artículos del menú'),
        ),
    ]
