<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-07-17 20:10

import django.core.validators
import django.db.models.deletion
=======
# Generated by Django 5.0 on 2025-07-17 20:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
>>>>>>> c67fd5f (<feat>[add the view of menu]: <description>)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('inventory', '0001_initial'),
=======
        ('clients', '0001_initial'),
        ('inventory', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> c67fd5f (<feat>[add the view of menu]: <description>)
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del menú')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_menu', models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('MERIENDA', 'Merienda'), ('CENA', 'Cena'), ('ESPECIAL', 'Menú Especial')], max_length=20, verbose_name='Tipo de menú')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'ordering': ['tipo_menu', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad requerida')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='Artículo de inventario')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='Menú')),
            ],
            options={
                'verbose_name': 'Artículo del menú',
                'verbose_name_plural': 'Artículos del menú',
                'unique_together': {('menu', 'inventory_item')},
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='items',
<<<<<<< HEAD
            field=models.ManyToManyField(related_name='menus', through='menus.MenuItem', through_fields=('menu', 'inventory_item'), to='inventory.inventory', verbose_name='Artículos del menú'),
=======
            field=models.ManyToManyField(related_name='menus', through='menus.MenuItem', to='inventory.inventory', verbose_name='Artículos del menú'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de entrega')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PROCESO', 'En Proceso'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado del pedido')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total del pedido')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clients.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PROCESO', 'En Proceso'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=20, null=True, verbose_name='estado anterior')),
                ('new_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PROCESO', 'En Proceso'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='nuevo estado')),
                ('notes', models.TextField(blank=True, help_text='Información adicional sobre este cambio de estado', verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='cambiado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='menus.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'historial de pedido',
                'verbose_name_plural': 'historial de pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='menus.menu', verbose_name='Menú')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Ítem de pedido',
                'verbose_name_plural': 'Ítems de pedido',
            },
>>>>>>> c67fd5f (<feat>[add the view of menu]: <description>)
        ),
    ]
