# Generated by Django 5.0 on 2025-07-17 20:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_cliente_usuario'),
        ('menus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Artículo del menú', 'verbose_name_plural': 'Artículos del menú'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='menus',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas adicionales'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tipo_menu',
            field=models.CharField(choices=[('DESAYUNO', 'Desayuno'), ('ALMUERZO', 'Almuerzo'), ('MERIENDA', 'Merienda'), ('CENA', 'Cena'), ('ESPECIAL', 'Menú Especial')], max_length=20, verbose_name='Tipo de menú'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad requerida'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='Menú'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='clients.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PROCESO', 'En Proceso'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado del pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total del pedido'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='menus.menu', verbose_name='Menú'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PROCESO', 'En Proceso'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=20, null=True, verbose_name='estado anterior')),
                ('new_status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('EN_PROCESO', 'En Proceso'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='nuevo estado')),
                ('notes', models.TextField(blank=True, help_text='Información adicional sobre este cambio de estado', verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='cambiado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='menus.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'historial de pedido',
                'verbose_name_plural': 'historial de pedidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
